### ISSUE TITLE
Allow changing filename on save

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/aia-eia-js#100]
Allow the user to set the name of the file being saved.

**Comment by MrDeshaies** [comment]
For the JSON file throughout, and the French/English PDF on the results page.

**Comment by Ancentury** [comment]
This is per Browser settings, not with the code. Here is the steps for Chrome, similar in other browsers.

1. go to top right corner, click three dots, 
2. in settings, click left side advanced, then download; 

or directly input in address bar: chrome://settings/downloads, 

you will find "Ask where to save ...", enable it.
![image](https://user-images.githubusercontent.com/1843015/151096710-ebd751b9-d666-473e-8fc6-1f13ba47e9b8.png)

If you find "Open certain file types ...", then click Clear. It will disable automatically open PDF file.
![image](https://user-images.githubusercontent.com/1843015/151097298-68fca269-30b4-4d6c-9581-4c6194230e0c.png)

After changing those settings, you should see the save as dialog when you click save or export button.

**Comment by MrDeshaies** [comment]
Instead of using a download link, could we switch it to the [File System Access API](https://web.dev/file-system-access/) (when it is available), or maybe a library wrapping this?

```js
const saveOptions = {
  suggestedName: 'AIA Results.json',
  types: [{
    description: 'JSON',
    accept: {
      'application/json': ['.json'],
    },
  }],
};

const handle = await self.showSaveFilePicker(saveOptions);
const fileHandle = await window.showSaveFilePicker();
const fileStream = await fileHandle.createWritable();
await fileStream.write(new Blob(["CONTENT"], {type: "text/plain"}));
await fileStream.close();
```
