### ISSUE TITLE
Run the demo by docker does not work

### ISSUE THREAD

**Issue by fgomezotero** [canada-ca/aia-eia-js#110]
We cloned the repository and executed the steps explained to run the demo with docker.

Once we access with the browser the URL http: // localhost: 8080 does not show the necessary options (image attached).
![aiabydocker](https://user-images.githubusercontent.com/2965157/58584958-daf2df80-822d-11e9-9767-c94b0f010bba.jpeg)

**Comment by gcharest** [comment]
Thanks for letting us know! Will be looking into it shortly.

I remember seeing the issue before.

**Comment by gcharest** [comment]
@CalvinRodo Would you happen to know how to fix this issue?

**Comment by CalvinRodo** [comment]
This is probably tied to the change that I had to make to get it working with github pages. 

In the `vue.config.js` file there is a line where if the NODE_ENV is set to "production" it sets the public_path to `"/aia-eia-js/"`

so the solution is either to remove that line, set the NODE_ENV to dev in the docker file or run it using `node run serve`, or we need to figure out another environment variable to use for github pages.

**Comment by fgomezotero** [comment]
Dear,

Modify the Dockerfile in order to build an image in Openshift through a buildconfig from a Dockerfile.

Dockerfile:
`FROM node:lts-alpine
COPY ./ /app
WORKDIR /app
RUN npm install 
#&& npm run build

#FROM nginx
#RUN mkdir /app
#COPY --from=0 /app/dist /app
#COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080
CMD ["npm","run","serve"]`

I also had to make some modifications to the vue.config.js file so that it would work for me in Openshift.

`module.exports = {
  //THere are some known issues with multi-page apps
  //jand using HTML history.pushState routing
  /*publicPath: "./",*/
  publicPath: process.env.NODE_ENV === "production" ? "/aia-eia-js/" : "/",
  devServer: {
    host: '0.0.0.0',
    disableHostCheck: true,
    port: 8080 
    },
  configureWebpack: {
    devtool: "source-map"
  }
};`

Thank you very much for your help!,
Regards
