### ISSUE TITLE
Documentation bug: customising the questions

### ISSUE THREAD

**Issue by tomslee** [canada-ca/aia-eia-js#114]
This is a really interesting project: thanks for making it public.

I'm happy with python but not a JavaScript developer. I am unsure which files to change to modify the questions in the survey. Do I make a copy of plainData.json and upload it through the "Choose File" button to test it out?

**Comment by gcharest** [comment]
Hi Tom!

Yes, I'm working on better documentation.

Essentially, we're using the survey.json to set the structure of questions
and answers with Survey.js

The next step is using custom coded scoring.

We definitely need more work on docs but also to make it more configurable.

Haven't had a chance to make said changes yet but getting to it shortly

Thanks!

Le mer. 17 juill. 2019 16 h 56, Tom Slee <notifications@github.com> a
écrit :

**Comment by tomslee** [comment]
Thanks! I'll look through those files and see what I can get from them.
