### ISSUE TITLE
Q: Government of Canada SVG file in header

### ISSUE THREAD

**Issue by tomslee** [canada-ca/aia-eia-js#115]
A question not an issue, but don't know where else to ask.

I've tried to locate where the Government of Canada image comes from so I can change it after forking this project. Any help welcome...

**Comment by tomslee** [comment]
Found it: I guess it is pulled in through this part of src/public/index.html

 ```
<script type="text/javascript"
    src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_30/cdts/compiled/soyutils.js"></script>

```

**Comment by gcharest** [comment]
Yes! Sorry, meant to reply.

We're using the standard WXT.

Le mar. 23 juill. 2019 16 h 26, Tom Slee <notifications@github.com> a
écrit :
