### ISSUE TITLE
Versions displayed mismatched

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#119]
When you load the AIA, the title at the top says "Algorithmic Impact Assessment v0.7", and the version in the footer below date modified says "Version: 0.0.4". It's confusing.

**Comment by gcharest** [comment]
Interesting, will double check to confirm whether that's the WXT footer version or the AIA version.

Might also need to remove version number from AIA altogether.

**Comment by MrDeshaies** [comment]
Having some version number, both while filling out and in the results, is important imho. As the tool evolves over time and the results get published, it would be good to know which version was used to conduct a particular assessment. The json result doesn't include the version, it would be good to add it (i'll create a separate ticket)

**Comment by gcharest** [comment]
Ah yeah, I agree. Might just want to make it less "in your face"?

**Comment by MrDeshaies** [comment]
Current title and footer match. Closing. Will create a separate item for the results.
