### ISSUE TITLE
Fix gh-pages build

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#12]
Current gh-pages build doesn't render the survey.

**Comment by KingBain** [comment]
ditch the typescript would love to help but I've never worked with Vue.JS or Typescript at all.

Can you simplify your technology stack ? :D

**Comment by gcharest** [comment]
TypeScript = typed JavaScript basically

Re: simplifying
We kind of did... :yum:

**Comment by gcharest** [comment]
Changed the build path in cdc352c9f4ffa3da1f31895685869ec29d219754
