### ISSUE TITLE
Save button missing on Results page

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#120]
Once you "Complete" the AIA, the Results page is missing a Save button to download the json. This feature is only available as you complete the AIA, on pages 1-13.

It would be really helpful to be able to save from the Results page. Remembering to save on the last page before Completing is not very user-friendly.

Saving/Loading the JSON is useful for people to pass around the results, and will be crucial when we look at publishing the results on open.canada.ca later.

**Comment by gcharest** [comment]
Good point!

**Comment by MrDeshaies** [comment]
The save button is there and works... But this change also carried over the upload ("choose file") and start again buttons which don't work as expected.

Choose file: uploading a file updates some of the information on the results page (the green score bar), but not the results page per-se.

Start again: should go back to the start screen, but it stays on the result screen and keeps the results previously entered.

Remove the upload and restart button from the results screen if that's an easy thing? As part of #133 new download buttons may be required; could be addressed as part of that as well.
