### ISSUE TITLE
Reminder that data is not saved

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#127]
**Is your feature request related to a problem? Please describe.**
Users have provided feedback stating that people are scared that data put in the form are being recorded and saved somewhere. This isn't the case and we note it on the first page but it may not be sufficient. 

**Describe the solution you'd like**
It would be useful to add reminders at the Results page and when closing the page (you will be losing all data).

**Comment by MrDeshaies** [comment]
Actually... The page leverages local storage, and that stays despite closing the page/browser. Data IS being saved locally. The local storage key is named "vuex"

**Comment by gcharest** [comment]
Right, but data isn't saved in a DB somewhere. Should be clarified for end
users who believe you're actually recording their answers right now 😉

Le lun. 19 août 2019 17 h 15, MrDeshaies <notifications@github.com> a
écrit :

**Comment by MrDeshaies** [comment]
Right. In this case, Big Brother isn't watching.

**Comment by KingBain** [comment]
However there is the potencial for data to be sent to webstat engines. Its mentioned in #77 that their are CDTS tracking codes in wet-en.js . I believe these could be used to track the form data

**Comment by ShadeWyrm** [comment]
@MrDeshaies 

How's this?:

"Information in the AIA is only stored locally, and the Government of Canada does not have access to the information you place into the tool. If you wish to retain your state, please save the data locally for future use."

**Comment by MrDeshaies** [comment]
I'd only add "locally **on your computer**" in case people are not clear on what locally means...

Information in the AIA is only stored locally on your computer, and the Government of Canada does not have access to the information you place into the tool. If you wish to retain your state, please save the data locally for future use.

Et en français:
Les informations contenues dans l'EIA ne sont stockées que localement sur votre ordinateur et le gouvernement du Canada n'a pas accès aux informations que vous placez dans l'outil. Si vous souhaitez conserver votre état, veuillez enregistrer les données localement pour une utilisation future.
