### ISSUE TITLE
Add Alternate Language Field for Complete AIA

### ISSUE THREAD

**Issue by ShadeWyrm** [canada-ca/aia-eia-js#132]
The AIA Tool needs to support bilingual data entry.

As part of the MVP :
- After Results, provide fields to enter all free-text entry in the alternate language.
- After the alternate language is provided, a final Report showing both languages.

So workflow:
AIA -> Summary -> Translations  -> Final Report (Bilingual)

**Comment by ShadeWyrm** [comment]
The following fields will need to be made available:

Page 1:
Respondent Details:
* Job Title

Project Details:
* Branch
* Project Title
* Departmental Program?
* Project Description

Page 2: 
Business Driver:
* Other Text Field

Page 5: 
About the System:
* Other Text Field

Page 7:
About the Decision:
* Other Text Field

Page 8:
* Please describe why the impacts resulting from the decision are as per selected option above.
* Please describe why the impacts resulting from the decision are (as per selected option above).
* Please describe why the impacts resulting from the decision are (as per selected option above)
* Please describe why the impacts resulting from the decision are (as per selected option above)
* Please describe why the impacts resulting from the decision are (as per selected option above)

Page 10:
Internal Stakeholders:
* Other Text Field
External Stakeholders:
* Other Text Field

**Comment by ShadeWyrm** [comment]
### Proposed Design

**Create a new file:**
survey-enfr-translate.json

Containing only the questions that are necessary for translation - if the file is empty then the summary and translate sections do not appear. (For countries with only a single language)

**Update the en/fr.json** files with text associated with Translation eg: "To complete the AIA Assessment you are required to provide translations for the following content."

**Create a new file:**
views/Summary.vue

A copy of the Results.vue. TBD on if any content is stripped out.

**Create a new file:**
views/Translate.vue

Largely a copy of Home.vue, but instead of modifying the this.$store.state.toolData object, add to this.$store.state.toolTranslations object.

**Update store.ts** to handle the new toolTranslations object.

**Update ActionButtonBar.vue** to cause the save function to save and load the toolTranslations objects.

**Update Results.vue** to display English AND French Content on same page, with data from toolTranslations.

@gcharest / @nschonni  - looking for a Sanity check, just as I'm not super experienced with Vue.

**Comment by nschonni** [comment]
I'm not sure if we need much that is view specific or not. When I was going through the docs and kicking the WYSIWYG, survey.js looked like it can tie visibility of a question on a page based off of other answers. EX: on the summary page, question13_translation could be shown if question13 isn't empty. Might be good to document if a suffix or some other pattern should be followed when adding those questions.
Might want to figure out if we just suffix those

**Comment by ShadeWyrm** [comment]
The issue with that approach is needing to support the summary section which can't be injected easily into the Survey. May be possible, but I'm not sure if it'd be easier or harder.
