### ISSUE TITLE
Checkbox question points not shown in results

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#215]
The results page doesn't show points for questions which have multi-select checkbox. For example, the answers to "Does the decision pertain to any of the categories below (check all that apply):" and "What types of unstructured data?" contribute to the score, but there is no score displayed next to them in the results.

Note that this is a display thing only; the computed score and level correctly consider the contribution of these questions.

![image](https://user-images.githubusercontent.com/53863781/80406579-499f4980-8892-11ea-9289-2eb66c5fce2b.png)

**Comment by MrDeshaies** [comment]
[multi-select.json.txt](https://github.com/canada-ca/aia-eia-js/files/4541387/multi-select.json.txt)

JSON file that can be used to reproduce.

**Comment by ShadeWyrm** [comment]
What should it be showing?

**Comment by MrDeshaies** [comment]
I think next to each selection, the number of points contributed should be shown. Or for the question, show the total. E.g. "What type of unstructured data" could show 6, or "Audio" 2 and "Images" 4.
