### ISSUE TITLE
Multi-select shows wrong values in export result

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#227]
Multi-select do not show the right values in the "export" section of the result page. The top-section (main results) are correct however.

Example from main results:
![image](https://user-images.githubusercontent.com/53863781/81322847-8b827980-9062-11ea-91cd-b2baa046d2bd.png)

And the corresponding section in the English Export. Note how other has been replaced with Economic Interests, and the presence of a "please describe" despite the absence of other.
![image](https://user-images.githubusercontent.com/53863781/81322939-a9e87500-9062-11ea-88dc-a278b39228fd.png)

[multi-select-wrong-in-pdf.json.txt](https://github.com/canada-ca/aia-eia-js/files/4594541/multi-select-wrong-in-pdf.json.txt)

**Comment by ShadeWyrm** [comment]
To review and test, is now live on the github url.

**Comment by MrDeshaies** [comment]
Works like a charm now! Thank you @ShadeWyrm
