### ISSUE TITLE
Initial feedback from user testing

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#26]
Numbering of the questions : either make disabled or have numbering consistent?

Scoring: review all questions and panels names to ensure scoring adds properly (question with images and text was a Y/N question and had scoring added)

* Need to add a landing page and have the comments linked to it rather than the survey app itself
  * Comments: Ashley and Noel to deal with it.

During survey, need to add: 

* Score: need to add current level (1-4)

Results page

* Need to add current level (1-4)
* Need to break out the sections on last page
* Need to add more information about the final level
* Need to be able to save as PDF
* Need to be able to save as *CSV/JSON
  * CSV preferred for proactive disclosure: however needs to have a continuous structure of the data
* Can they save their AIA and reload later? Not sure
* Add Canada.ca headers and footers + breadcrumbs
* Need a list of what they see the tool being able to do. Might be beyond the library itself

Open Gov is working with SCMA for blogging site

**Comment by gcharest** [comment]
Need to break out in manageable issues.

**Comment by CalvinRodo** [comment]
So with some of these changes we'll need to find a different hosting solution then GitHub Pages. 

Saving as PDF might be a bit difficult to sort out without a server to handle the processing. 

We should be able to do some sort of import/export since SurveyJS already has that functionality. 

Export as JSON should be easy, but as CSV might be a bit more work.

**Comment by gcharest** [comment]
OK, i think we can skip PDF for view and aim for the JSON for now. 

Regarding the CSV, I'm pretty sure there's some library available from JSON

I'll continue creating the issues but I'll also prioritize them.

**Comment by gcharest** [comment]
Also, just talked to team at Open Government and they're going to be able
to setup a Drupal page on the website so we'll have better hosting options

Le ven. 29 mars 2019 16 h 56, Calvin Rodo <notifications@github.com> a
écrit :

**Comment by gcharest** [comment]
Just understood what you meant by hosting, please disregard previous comments about export to PDF 😉

**Comment by gcharest** [comment]
Might be interesting for PDF generation:

https://github.com/MrRio/jsPDF
