### ISSUE TITLE
Exporting to PDF Issue

### ISSUE THREAD

**Issue by andreww1977** [canada-ca/aia-eia-js#265]
**Describe the bug - Décrivez le bogue**
We have completed an AIA and are trying to export it to PDF.  There is an issue on page 5 of the survey.  When "Process optimization & workflow automation: Analyzing large data sets to identify and anomalies, cluster patterns, predict outcomes or ways to optimize; and automate specific workflows" is checked off it breaks the export function for PDF at the end of the survey.

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Go to page 5 of the survey
2. Click on "Process optimization & workflow automation: Analyzing large data sets to identify and anomalies, cluster patterns, predict outcomes or ways to optimize; and automate specific workflows" 
3.  Finish the survey
4. Export to PDF.

![AIA Issue Capture](https://user-images.githubusercontent.com/66420427/83753628-09757880-a641-11ea-8bb2-ed5452c19d25.JPG)

**Expected behavior**
The export to PDF should work at the end of the survey.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Edge

**Comment by MrDeshaies** [comment]
This is the same issue as #264 ; we'll have a fix deployed shortly

**Comment by MrDeshaies** [comment]
The version hosted on github has been fixed. Please force a refresh: [https://canada-ca.github.io/aia-eia-js/](https://canada-ca.github.io/aia-eia-js/)

We'll get that version on open.canada.ca shortly.
