### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#27]
Need to add a landing page for the Open Government portal and have the comments linked to it rather than the survey app itself. 

There's a feature in the app for a first page but it probably would need to be separated so that comments aggregate on the home page rather than under the survey.

**Comment by gcharest** [comment]
Further clarification with the dev team at Open Gov needed but the landing page could be something like the text at the following link, preceding the questions.

The reason for a separate first page than the one provide by the SurveyJS library is that it would be part of the app and comments would make for a very long page.

It might prove more practical for others wanting to leverage the app for other purposes.

**Comment by MrDeshaies** [comment]
We built a landing page at
https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/responsible-use-ai/algorithmic-impact-assessment.html
