### ISSUE TITLE
only english locale

### ISSUE THREAD

**Issue by aortiz-arroyo** [canada-ca/aia-eia-js#279]
Hello- Trying to figure out or get help on what needs to be done to use English only as locale.

**Comment by gcharest** [comment]
Hi! That's a good question, I think the default is made to support both EN/FR as those are the two official languages in Canada.

The trigger is set in https://github.com/canada-ca/aia-eia-js/blob/master/src/plugins/i18n.ts if I remember correctly, I'll have to look a bit closer shortly.

**Comment by MrDeshaies** [comment]
The AIA will continue to be bilingual French/English, as it is a requirement for apps built by the federal government. If you desire an English-only version, I would encourage you to fork and change the template used, removing references to Canada and the switch language link. Thanks.
