### ISSUE TITLE
Add Canada.ca headers, footers and breadcrumbs

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#30]
In order for the application to be hosted, the dev team at Open Gov recommended that these components be present.

I don't think the open gov portal has moved to the more recent version of WET though.

**Comment by gcharest** [comment]
The implementation is not yet decided, will wait on @thriuin input on how to move forward with this issue.

**Comment by thriuin** [comment]
I'm fine with going with the GCWeb 2,0 theme for this.

**Comment by gcharest** [comment]
closed on #92
