### ISSUE TITLE
"Next" button does nothing on last page

### ISSUE THREAD

**Issue by rimrk** [canada-ca/aia-eia-js#360]
**Describe the bug - Décrivez le bogue**
The final page of the AIA questionnaire prints a "Next" button along with a "Complete" . The "Next" does not lead anywhere. Remove "Next"

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Go to page 13 of the AIA Questionnaire 
2. Click on 'Next'
3. See error - nothing happens.

**Expected behavior**
Remove "Next" to avoid clutter

**Comment by MrDeshaies** [comment]
Remove, or disable the control
