### ISSUE TITLE
Result page labelling of section title

### ISSUE THREAD

**Issue by rimrk** [canada-ca/aia-eia-js#361]
**Describe the bug - Décrivez le bogue**
Results page
Section 1 - "On this page"
The sections that could be found on the page are listed, I would like them to be labelled appropriately. 

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Complete an AIA
2. Navigate to the Results page
3. Scroll down to "On this page"

**Expected behavior**
Label the sections

Section 1: Impact Level Result
Section 2: Requirements Specific to Impact Level
Section 3: Mitigations Measures
Section 4: Questions and Answers
Subsection 4.1: Project Details
Subsection 4.2: Impact Questions and Answers
Subsection 4.3: Mitigation Questions and Answers

**Comment by MrDeshaies** [comment]
Hi @rimrk , I'm not clear what is being asked here. Are you asking for sections titles to be preceded with "Section #:", e.g. Section 1, Section 2, etc. ?

**Comment by rimrk** [comment]
Hi @MrDeshaies yes! I am asking for a mini table of contents to the page.
