### ISSUE TITLE
Results formatting of Questions & Answers

### ISSUE THREAD

**Issue by rimrk** [canada-ca/aia-eia-js#364]
**Describe the bug - Décrivez le bogue**
The formatting of the Questions and Answers Page. Currently the page is displayed as :

![Screen Shot 2020-09-21 at 9 38 58 AM](https://user-images.githubusercontent.com/64172337/93774056-d1457600-fbee-11ea-90ce-6feccb17919a.png)

Changes required:
1. Titles to be distinct, with a space between them and the questions
2. Questions to be numbered
3. The points should be assigned to the answers not the questions

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:

1. Go to the results page of the AIA
2. Scroll down to Questions & Answers
3. See all answers

**Expected behavior**
Numbered questions and points assigned to answers

**Comment by MrDeshaies** [comment]
See #363 for discussion on numbering
