### ISSUE TITLE
Page number bar 

### ISSUE THREAD

**Issue by rimrk** [canada-ca/aia-eia-js#366]
**Describe the bug - Décrivez le bogue**
The page number bar on the first question page of the AIA displays page 1 of 9 when it should be page 1 of 13.

![Screen Shot 2020-09-21 at 10 16 10 AM](https://user-images.githubusercontent.com/64172337/93778074-7d895b80-fbf3-11ea-845c-dcd1842d8811.png)

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Go to the first question page of the AIA

**Comment by MrDeshaies** [comment]
This is because some pages are filtered based on Design/Implementation. Once this question is answered, it jumps to 13... That explains it, but doesn't make it right! I agree that this needs to be addressed.
