### ISSUE TITLE
Canada.ca Template transtions

### ISSUE THREAD

**Issue by e-wu** [canada-ca/aia-eia-js#39]
The template translations are not occurring. When the fragments are added, it is still inserting English values. 

Example at bottom of every page:
- Date modified
- Report a problem on this page

Links to #30, #7, #6, #38

**Comment by gcharest** [comment]
The template transition is called on line [20](https://github.com/canada-ca/aia-eia-js/blob/cb14eb24516d5a7e818724ebc00d072ca694fa6a/public/index.html#L20) of the Index.

```html
<script type="text/javascript"
    src="https://www.canada.ca/etc/designs/canada/cdts/gcweb/v4_0_30/cdts/compiled/wet-en.js"></script>
```

**Comment by gcharest** [comment]
I should say "Isn't called". Need to add a condition there to update the link wet-en to wet-fr.

**Comment by CalvinRodo** [comment]
yeah it would probably be easier to have an index-en and an index-fr then using js, i tried to load it dynamically and I can't get it to work this is a pain.

**Comment by MrDeshaies** [comment]
Recaptured (with screenshots!) as #650 ; closing this one.
