### ISSUE TITLE
Potential logic error regarding display of question 22

### ISSUE THREAD

**Issue by rbad** [canada-ca/aia-eia-js#40]
In testing the currently deployed version on https://canada-ca.github.io/digital-playbook-guide-numerique/views-vues/automated-decision-automatise/en/algorithmic-impact-assessment.html (as of 2019.04.05) while filling out the form describing a low impact application (see attached JSON file for answers provided), when reaching question 22 it showed the question as being blank.

<img width="1306" alt="Screenshot 2019-04-05 at 11 25 14 am" src="https://user-images.githubusercontent.com/15617911/55648995-9d765680-5796-11e9-89a9-d16be68e4b1d.png">

[aia-form-state.json.zip](https://github.com/canada-ca/aia-eia-js/files/3049205/aia-form-state.json.zip)

**Comment by gcharest** [comment]
Thanks for letting us know, we'll look into it shortly!

Guillaume

**Comment by gcharest** [comment]
Hi @rbad !

I had a minute to look a bit more into it and the project you link to is the former one which is now deprecated. I'll update the title to that published version as so as it's no longer maintained.

We have moved from the previous version which was embedded in the Draft Digital Playbook.

If you'd like to test the current demo, please use the following link: https://canada-ca.github.io/aia-eia-js/

Thanks!

Guillaume
