### ISSUE TITLE
"Previous" button does nothing on first page 

### ISSUE THREAD

**Issue by SalimErradi** [canada-ca/aia-eia-js#427]
Describe the bug - Décrivez le bogue
The first page of the AIA questionnaire prints a "Previous" button. The "Previous" does not lead anywhere. Remove "Previous"

To Reproduce - Pour reproduire
Steps to reproduce the behavior - Étape pour reproduire le comportement:

Go to page 1 of the AIA Questionnaire
Click on 'Previous'
See error - nothing happens.
Expected behavior
Remove "Previous" to avoid clutter

**Comment by MrDeshaies** [comment]
This was included in a PR.  The first page removes the "Previous" button, and the last page removed the "Next" button. Works well in both languages.  Closing.
