### ISSUE TITLE
Add  UnitTests for Store.ts

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/aia-eia-js#45]
Unit tests should be added for the score.ts file since it's fairly complex and we don't want to break the functionality when refactoring, or adding new features.

**Comment by KOVCHENKO** [comment]
The new pull request has been proposed for this issue: https://github.com/canada-ca/aia-eia-js/pull/47

**Comment by CalvinRodo** [comment]
Thanks @KOVCHENKO I'll do a review of the PR today

**Comment by gcharest** [comment]
Just an update to confirm review in undergoing. Thanks!

**Comment by gcharest** [comment]
Fix in #47
