### ISSUE TITLE
Locale Text For French PDF Not Showing

### ISSUE THREAD

**Issue by SalimErradi** [canada-ca/aia-eia-js#542]
**Describe the bug - Décrivez le bogue**
Under "Details of Project" for the French PDF results, does not show French details corresponding multiple fields. 

**To Reproduce - Pour reproduire**
Steps to reproduce the behavior - Étape pour reproduire le comportement:
1. Go to results
2. Open French PDF and see fields populated.

**Expected behavior**
See fields populated.

![image](https://user-images.githubusercontent.com/16595047/103224107-3fd45700-48f5-11eb-99f1-3f2321ccac76.png)

Fields should be populated like the English PDF.

![image](https://user-images.githubusercontent.com/16595047/103224580-e91b4d00-48f5-11eb-9351-9196021dbd74.png)

**Comment by MrDeshaies** [comment]
This was mostly fixed by another PR... But the project phase is still missing.
![image](https://user-images.githubusercontent.com/53863781/107824633-cb902e80-6d4f-11eb-93bd-dada02ecf250.png)
