### ISSUE TITLE
Raw Risk score calculation (mitigation modifier)

### ISSUE THREAD

**Issue by NoelCorriveau** [canada-ca/aia-eia-js#59]
Change the mitigation modifier to decrease raw risk score by 15% (rather than 10 points)

**Comment by NoelCorriveau** [comment]
Can this be for 0.5

**Comment by gcharest** [comment]
Similar to #60 

Need to change hardcoded modifiers by variables in store.ts

Current calculation is:

```Javascript
 if (mitigationScore >= percentage * maxMitigationScore) {
    total = rawRiskScore - deduction;
  } else {
    total = rawRiskScore;
  }
```

`deduction` will need to be changed to a percentage (0.15)

Then the `total`will need to be calculated on `rawRiskScore - rawRiskScore * deduction`

**Comment by gcharest** [comment]
Actually, should be `(1-deduction) * rawRiskScore`
