### ISSUE TITLE
Multi-Lingual Survey

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/aia-eia-js#6]
The survey must be bilingual

Instructions on how to create a multingual survey using Survey.io can be found here:
https://surveyjs.io/Examples/Library/?id=survey-multilanguages&platform=Vue&theme=default

**Comment by gcharest** [comment]
I've started putting the full tranlsation in the JSON, will need the dropdown to switch from EN to FR and vice-versa.

**Comment by gcharest** [comment]
This is done for the Survey. Closing
