### ISSUE TITLE
Raw Risk Score modification (risk levels)

### ISSUE THREAD

**Issue by NoelCorriveau** [canada-ca/aia-eia-js#60]
Change risk level determinations by percentage rather than number score.
Level 1 25%  Level 2: 50% level 3 75% level 4 100%

**Comment by gcharest** [comment]
We'll need to change the way we calculate the overall scoring. Currently, the max score is hardcoded.

For this, we'll need to cycle through all answers of all questions for both the panels with RS suffix, identify the max possible value and then add them for the maxPossibleScore.

This will allow us to change dynamically the scoring and thresholds of the scoring.

**Comment by gcharest** [comment]
Example of current scoring:
```Javascript
  if (total <= 18) {
    level = 1;
  } else if (total > 18 && total <= 36) {
    level = 2;
  } else if (total > 36 && total <= 54) {
    level = 3;
  } else {
    level = 4;
  }
```

Should be changed by:

```Javascript
  if (total <= maxPossibleScore * threshold1) {
    level = 1;
  } else if (total > maxPossibleScore * threshold1 && total <= maxPossibleScore * threshold2) {
    level = 2;
  } else if (total > maxPossibleScore * threshold2 && total <= maxPossibleScore * threshold3) {
    level = 3;
  } else {
    level = 4;
  }
```
Where `threshold*` is a percentage (e.g.: 0.25, 0.5, 0.75)
