### ISSUE TITLE
Update Design AIA (new questions)

### ISSUE THREAD

**Issue by NoelCorriveau** [canada-ca/aia-eia-js#61]
new questions have been added to the design phase AIA

**Comment by gcharest** [comment]
Could you please add the link to the spreadsheet here?

Thanks!

Le mer. 8 mai 2019 14 h 11, NoelCorriveau <notifications@github.com> a
écrit :

**Comment by NoelCorriveau** [comment]
https://docs.google.com/spreadsheets/d/1x_JaBwiQD0PmLNke1JKaqCVbG8DuC4ZZFQs7El12bWg/edit#gid=590222988

**Comment by gcharest** [comment]
Questions have been updated in #64
