### ISSUE TITLE
Clarification boxes 

### ISSUE THREAD

**Issue by NoelCorriveau** [canada-ca/aia-eia-js#63]
Is there a way to call on a text box to provide additional clarification or details for questions?

**Comment by gcharest** [comment]
Yes, there is a way to add information on questions. There's a description value that can be used to describe further the question. I've added on on the very first question for you to see. 

We'll need a list of questions as well as the required descriptions.

**Comment by gcharest** [comment]
Confirmed that the description under the text is acceptable at this point.
