### ISSUE TITLE
Missing footer translations

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#650]
The French footer is missing a few translations.

1. Date modified (Date de modification)
2. Contact Information - Terms and conditions - Privacy (Contactez-nous / Avis / Confidentialité)
3. The button "Report a problem on this page" (Signaler un problème sur cette page)

![image](https://user-images.githubusercontent.com/53863781/112871843-ac462a00-908d-11eb-8364-6a414218a1bd.png)

**Comment by MrDeshaies** [comment]
#39 is a duplicate

**Comment by Ancentury** [comment]
@MrDeshaies The translations have been fixed. Also fixed their related links.
