### ISSUE TITLE
Loading saved file in different language

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#69]
If user saves JSON in English then load results in French app or vice-versa, questions will be mixed up.

**Comment by CalvinRodo** [comment]
Which questions have this problem?

**Comment by gcharest** [comment]
Tested the ones after Project details page: Basically any question that is not Comment based

**Comment by gcharest** [comment]
Nope, this is not the issue. It's simply that the JSON hasn't been translated.
