### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/aia-eia-js#7]
The app must support multiple languages.

Here is some stuff that may help for Vue

https://github.com/kazupon/vue-i18n
https://medium.freecodecamp.org/how-to-add-internationalization-to-a-vue-application-d9cfdcabb03b

**Comment by CalvinRodo** [comment]
Related to #6

**Comment by gcharest** [comment]
Partially completed, missing the landing page and the Head part (e.g.: site Title)
