### ISSUE TITLE
Add traffic metrics

### ISSUE THREAD

**Issue by gcharest** [canada-ca/aia-eia-js#77]
Need to start tracking metrics on the deployed AIA.

Could use Google Analytics or any other, need to setup an account though.

**Comment by CalvinRodo** [comment]
I believe that the CDTS is already tracking metrics for anyone that is using their plugin we should be able to leverage that data or we can add our own. 

I'll reach out to Shawn Thompson here at ESDC tomorrow he should be able to provide insight

**Comment by shawnthompson** [comment]
We put GA in but never used it, yet or even looked at the data. Not sure how well it works. Presently all we track is hits to our JS files.

**Comment by gcharest** [comment]
Hmm, there's a request to track "usage" so we probably need to figure out that part.

**Comment by KingBain** [comment]
Was taking a look at this tonight. Looks like the best way to do AJAX tracking is with google tag manager and as mentioned by @shawnthompson there is a google tag manager tracking code embedded in the wet-en.js used by index.html. 

I dont know who really owns that tracking code(maybe CDTS?) but you may want to use a version of wet-en.js that doesn't have someone elses tracking code.

Th code
**GTM-5DBPCQJ**

Same goes for a google analytics tracking code  _not sure where this one is coming from yet_
**UA-118615027-1**

**Comment by shawnthompson** [comment]
@KingBain, yes the GTM and UA code are owned by us. One is Google Tag Manager and the other one is the universal Google Analytics. I'm guessing that's what UA standards for. We haven't really spent much time looking at the stats.

We were thinking of creating a variable to let apps put in their own tracking code.

CC: @fredymoko, @nicolasraymond

**Comment by MrDeshaies** [comment]
There is no longer a need for this. 2 years of operations, and no one asked for usage data. The most significant KPI is how many AIAs are published on the open government portal.
