### ISSUE TITLE
Preserve newline character for narratives

### ISSUE THREAD

**Issue by MrDeshaies** [canada-ca/aia-eia-js#777]
Many narratives entered by users are quite long. Unfortunately, paragraphs entered in the input get rendered as a single line in the output, making it more difficult to read. This is to request that newlines entered in the multi-line free-text fields be preserved in the output (results page and PDF).

E.g. of input:
![image](https://user-images.githubusercontent.com/53863781/132542678-8f6df900-24aa-4639-9d27-19d959203ed7.png)

And how it currently gets rendered, with newlines removed.
![image](https://user-images.githubusercontent.com/53863781/132542768-f5caaa57-f401-4656-8617-d5b8b5034895.png)

**Comment by Ancentury** [comment]
@MrDeshaies Results page preserve newline and space has been fixed. However the pdf still not show the newline, I will investigate more. The branch is 777-preserve-newline if you want to see it.

**Comment by Ancentury** [comment]
@MrDeshaies PDF fixed too.
