### ISSUE TITLE
Read survey data from back end

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/aia-eia-js#8]
Currently the survey is read from the following file: 
https://github.com/canada-ca/aia-eia-js/blob/master/src/survey.json

We need to read the data from some sort of api, that should  be feeding data from some tool such as Google Docs or Airtable.

**Comment by gcharest** [comment]
Probably good enough for MVP.

Confirmed with the AIA team that they won't be making changes to the assessment tool on the fly.

**Comment by gcharest** [comment]
Useful documentation for this feature:

https://surveyjs.io/Examples/Library/?id=questiontype-dropdownrestfull

**Comment by gcharest** [comment]
https://surveyjs.io/Documentation/Library/#choicesByUrl

**Comment by MrDeshaies** [comment]
We're OK with maintaining the questions via JSON; no need for a Google Docs or other GUI. Questions change infrequently.
