### ISSUE TITLE
Print Results

### ISSUE THREAD

**Issue by CalvinRodo** [canada-ca/aia-eia-js#9]
We need to have the ability to print the results to a file so users can upload to the Open Data Portal.

**Comment by gcharest** [comment]
Need two version of the export files:
* Printable version (most likely PDF-like)
* Electronic version to be published on Open Data Portal (most likely CSV/JSON like)

Question: could the electronic version be imported to reload the answers done at a certain time?

Might need a proper versioning of published assessment tool (v0.3 survey only can reload results saved during v0.3).

**Comment by gcharest** [comment]
Related question: https://github.com/surveyjs/surveyjs/issues/1209

And working example: https://plnkr.co/edit/riq0aC5BCQRDYZiK?p=preview

**Comment by gcharest** [comment]
https://github.com/MrRio/jsPDF

**Comment by CalvinRodo** [comment]
Nice

**Comment by gcharest** [comment]
Technically, this can be done by Print as PDF in Windows 10, Linux or MacOS, like @e-wu mentioned earlier.

**Comment by KingBain** [comment]
This issue kind of tickles my brain. 

"print the results to a file" is a bit confusing as "printing" doesn't normally generate "files".

Couple thoughts:
Would it be better to have a "Print Page" button and view from the results page ?
Would a generate PDF report action/button be better ?

**Comment by MrDeshaies** [comment]
This has been fixed for a while; we get JSON as well as French/English PDF out of the results page.
